require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe NumbersController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # Number. As you add validations to Number, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # NumbersController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all numbers as @numbers" do
      number = Number.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:numbers)).to eq([number])
    end
  end

  describe "GET #show" do
    it "assigns the requested number as @number" do
      number = Number.create! valid_attributes
      get :show, {:id => number.to_param}, valid_session
      expect(assigns(:number)).to eq(number)
    end
  end

  describe "GET #new" do
    it "assigns a new number as @number" do
      get :new, {}, valid_session
      expect(assigns(:number)).to be_a_new(Number)
    end
  end

  describe "GET #edit" do
    it "assigns the requested number as @number" do
      number = Number.create! valid_attributes
      get :edit, {:id => number.to_param}, valid_session
      expect(assigns(:number)).to eq(number)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Number" do
        expect {
          post :create, {:number => valid_attributes}, valid_session
        }.to change(Number, :count).by(1)
      end

      it "assigns a newly created number as @number" do
        post :create, {:number => valid_attributes}, valid_session
        expect(assigns(:number)).to be_a(Number)
        expect(assigns(:number)).to be_persisted
      end
  
      it "does not redirect to the created number" do
        post :create, {:number => valid_attributes}, valid_session
        expect(response).to not redirect_to(Number.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved number as @number" do
        post :create, {:number => invalid_attributes}, valid_session
        expect(assigns(:number)).to be_a_new(Number)
      end

      it "re-renders the 'new' template" do
        post :create, {:number => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested number" do
        number = Number.create! valid_attributes
        put :update, {:id => number.to_param, :number => new_attributes}, valid_session
        number.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested number as @number" do
        number = Number.create! valid_attributes
        put :update, {:id => number.to_param, :number => valid_attributes}, valid_session
        expect(assigns(:number)).to eq(number)
      end

      it "redirects to the number" do
        number = Number.create! valid_attributes
        put :update, {:id => number.to_param, :number => valid_attributes}, valid_session
        expect(response).to redirect_to(number)
      end
    end

    context "with invalid params" do
      it "assigns the number as @number" do
        number = Number.create! valid_attributes
        put :update, {:id => number.to_param, :number => invalid_attributes}, valid_session
        expect(assigns(:number)).to eq(number)
      end

      it "re-renders the 'edit' template" do
        number = Number.create! valid_attributes
        put :update, {:id => number.to_param, :number => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested number" do
      number = Number.create! valid_attributes
      expect {
        delete :destroy, {:id => number.to_param}, valid_session
      }.to change(Number, :count).by(-1)
    end

    it "redirects to the numbers list" do
      number = Number.create! valid_attributes
      delete :destroy, {:id => number.to_param}, valid_session
      expect(response).to redirect_to(numbers_url)
    end
  end

end
